version: '3'
services:
  web:
    build: site
    ports :
     - "80:80"
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini

  database:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pa-iw
      POSTGRES_USER: pa-iw
      POSTGRES_PASSWORD: Response11

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  mailcatcher:
    restart: always
    image: dockage/mailcatcher:0.8.2
    ports:
       - "1080:1080"
       - "1025:1025" 

volumes:
  pgdata: